### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by gorterd** [GT458/fitbook#2]
Great work, Sohrob -- it's looking good!

- Note: I'll hold off on all CSS feedback for now (whenever you resubmit the card for review, just make sure to complete the styling first, now that we've had the CSS lecture)
- [x] You'll want to have a footer on the splash, but avoid deadlinks (e.g. no 'About' link to an about page that doesn't exist). So you'll want to replace the content with custom text content. For example, you could treat it as a mini-resume and list technologies, languages you know, etc.
- [x] Getting a 500 Internal Server Error when submitting the sign up form (with valid or invalid input)
- [x] You'll want the login errors to clear when opening the sign up form (no direct equivalent on FB, since it brings you to a new login page on invalid login attempt)
- [x] Demo login is getting a 401 response -- I'd make sure you've migrated and seeded your production db!
- [x] The birthday input in the sign up form doesn't allow selecting other day / month / year besides default 1 January 1999
- As a heads up, it looks like right now you are logging thunk actions as well. That won't cause any problems, but if you want to decrease console clutter, you could switch the order of logger and thunk when applying middleware while creating a store. 
- Note: I wasn't able to test bootstrapping current user or logout functionality

**Comment by GT458** [comment]
Hi Daniel, thanks for reviewing the user auth. I went ahead and addressed the issues you outlined. The database was not seeded properly and some necessary gems were under the development group. This fixed a majority of the issues brought up and the live site should be in working order for now.

**Comment by gorterd** [comment]
Awesome - sign up works for me now! Quick note -- if you could keep the issue open, I can then close it when I move your MVP over to done. Anyway, I took out the stuff you fixed, here's the updated feedback:

- Note: I'll hold off on all CSS feedback for now (whenever you resubmit the card for review, just make sure to complete the styling first, now that we've had the CSS lecture)
- [x] You'll want to have a footer on the splash, but avoid deadlinks (e.g. no 'About' link to an about page that doesn't exist). So you'll want to replace the content with custom text content. For example, you could treat it as a mini-resume and list technologies, languages you know, etc.
- [x] You'll want the login errors to clear when opening the sign up form (no direct equivalent on FB, since it brings you to a new login page on invalid login attempt)
- [x] The birthday input in the sign up form doesn't allow selecting other day / month / year besides default 1 January 1999
- As a heads up, it looks like right now you are logging thunk actions as well. That won't cause any problems, but if you want to decrease console clutter, you could switch the order of logger and thunk when applying middleware while creating a store.

**Comment by gorterd** [comment]
Awesome work, Sohrob, keep it up! Here's my additional feedback after reviewing CSS:
- [x] You'll want the footer (background) to extend to the bottom of the screen. Rather than hardcoding a height for both the app component and footer component, I'd set the height of one or both using relative viewport units ([vw and vh](https://css-tricks.com/fun-viewport-units/)) in combination with [calc](https://developer.mozilla.org/en-US/docs/Web/CSS/calc()).
- [x] The sign up form could use a bit more spacing (margins etc), & larger inputs and fonts (the sign up button padding should be a bit smaller). For example, the spacing between 'Sign Up' and 'It's quick and easy' should be expanded. (Reference real Facebook signup modal)
  - [x] Birthday and Gender labels within the sign up form are not left aligned.

**Comment by GT458** [comment]
Thanks for reviewing my sign up modal Daniel, I went ahead and implemented the changes you suggested.
